// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0-devel
// 	protoc        (unknown)
// source: simulate.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SimulateDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	D1 int64 `protobuf:"varint,1,opt,name=d1,proto3" json:"d1,omitempty"`
	D2 int64 `protobuf:"varint,2,opt,name=d2,proto3" json:"d2,omitempty"`
	D3 int64 `protobuf:"varint,3,opt,name=d3,proto3" json:"d3,omitempty"`
	D4 int64 `protobuf:"varint,4,opt,name=d4,proto3" json:"d4,omitempty"`
}

func (x *SimulateDataRequest) Reset() {
	*x = SimulateDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulateDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateDataRequest) ProtoMessage() {}

func (x *SimulateDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simulate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateDataRequest.ProtoReflect.Descriptor instead.
func (*SimulateDataRequest) Descriptor() ([]byte, []int) {
	return file_simulate_proto_rawDescGZIP(), []int{0}
}

func (x *SimulateDataRequest) GetD1() int64 {
	if x != nil {
		return x.D1
	}
	return 0
}

func (x *SimulateDataRequest) GetD2() int64 {
	if x != nil {
		return x.D2
	}
	return 0
}

func (x *SimulateDataRequest) GetD3() int64 {
	if x != nil {
		return x.D3
	}
	return 0
}

func (x *SimulateDataRequest) GetD4() int64 {
	if x != nil {
		return x.D4
	}
	return 0
}

type SimulateDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ok string `protobuf:"bytes,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *SimulateDataResponse) Reset() {
	*x = SimulateDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simulate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimulateDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateDataResponse) ProtoMessage() {}

func (x *SimulateDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simulate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateDataResponse.ProtoReflect.Descriptor instead.
func (*SimulateDataResponse) Descriptor() ([]byte, []int) {
	return file_simulate_proto_rawDescGZIP(), []int{1}
}

func (x *SimulateDataResponse) GetOk() string {
	if x != nil {
		return x.Ok
	}
	return ""
}

var File_simulate_proto protoreflect.FileDescriptor

var file_simulate_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x73, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x55, 0x0a, 0x13, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x64, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x32, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x64, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x33, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x64, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x64,
	0x34, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x64, 0x34, 0x22, 0x26, 0x0a, 0x14, 0x53,
	0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x6f, 0x6b, 0x32, 0x52, 0x0a, 0x0f, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3f, 0x0a, 0x08, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61,
	0x74, 0x65, 0x12, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x62,
	0x2e, 0x53, 0x69, 0x6d, 0x75, 0x6c, 0x61, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simulate_proto_rawDescOnce sync.Once
	file_simulate_proto_rawDescData = file_simulate_proto_rawDesc
)

func file_simulate_proto_rawDescGZIP() []byte {
	file_simulate_proto_rawDescOnce.Do(func() {
		file_simulate_proto_rawDescData = protoimpl.X.CompressGZIP(file_simulate_proto_rawDescData)
	})
	return file_simulate_proto_rawDescData
}

var file_simulate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_simulate_proto_goTypes = []interface{}{
	(*SimulateDataRequest)(nil),  // 0: pb.SimulateDataRequest
	(*SimulateDataResponse)(nil), // 1: pb.SimulateDataResponse
}
var file_simulate_proto_depIdxs = []int32{
	0, // 0: pb.SimulateService.Simulate:input_type -> pb.SimulateDataRequest
	1, // 1: pb.SimulateService.Simulate:output_type -> pb.SimulateDataResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_simulate_proto_init() }
func file_simulate_proto_init() {
	if File_simulate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simulate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulateDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simulate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimulateDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simulate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simulate_proto_goTypes,
		DependencyIndexes: file_simulate_proto_depIdxs,
		MessageInfos:      file_simulate_proto_msgTypes,
	}.Build()
	File_simulate_proto = out.File
	file_simulate_proto_rawDesc = nil
	file_simulate_proto_goTypes = nil
	file_simulate_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SimulateServiceClient is the client API for SimulateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SimulateServiceClient interface {
	Simulate(ctx context.Context, in *SimulateDataRequest, opts ...grpc.CallOption) (*SimulateDataResponse, error)
}

type simulateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSimulateServiceClient(cc grpc.ClientConnInterface) SimulateServiceClient {
	return &simulateServiceClient{cc}
}

func (c *simulateServiceClient) Simulate(ctx context.Context, in *SimulateDataRequest, opts ...grpc.CallOption) (*SimulateDataResponse, error) {
	out := new(SimulateDataResponse)
	err := c.cc.Invoke(ctx, "/pb.SimulateService/Simulate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimulateServiceServer is the server API for SimulateService service.
type SimulateServiceServer interface {
	Simulate(context.Context, *SimulateDataRequest) (*SimulateDataResponse, error)
}

// UnimplementedSimulateServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSimulateServiceServer struct {
}

func (*UnimplementedSimulateServiceServer) Simulate(context.Context, *SimulateDataRequest) (*SimulateDataResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Simulate not implemented")
}

func RegisterSimulateServiceServer(s *grpc.Server, srv SimulateServiceServer) {
	s.RegisterService(&_SimulateService_serviceDesc, srv)
}

func _SimulateService_Simulate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimulateDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimulateServiceServer).Simulate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.SimulateService/Simulate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimulateServiceServer).Simulate(ctx, req.(*SimulateDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SimulateService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.SimulateService",
	HandlerType: (*SimulateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Simulate",
			Handler:    _SimulateService_Simulate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simulate.proto",
}
